output-class: WhisprLocalizations
arb-dir: lib\lang\l10n
template-arb-file: intl_en.arb
output-localization-file: whispr_localizations.dart
synthetic-package: false # important, if you want to import the delegate in another package or app
output-dir: lib\lang\generated