// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:whispr/data/local/hive/hive_adapter/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AudioRecordingModelAdapter());
    registerAdapter(MoodAdapter());
    registerAdapter(RecordingTagModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AudioRecordingModelAdapter());
    registerAdapter(MoodAdapter());
    registerAdapter(RecordingTagModelAdapter());
  }
}
